### PR TITLE
User story 11

### PR DESCRIPTION
**Pull request by Hushtarr**
Lesson controller alomost done,need some field to be done from other user story for test it.

### CODE REVIEW

**Comment by Adela-cloud** [comment]
I think it’s correct, but not that sure. So, let’s wait for Cihat to review before merging.

**Review by mustafacihat — APPROVED** [review]
I want to approve this part, but I could not see how you have handled the validation part!!! With this structure the form will not work as expected!!!

**Comment by Hushtarr** [comment]
> I want to approve this part, but I could not see how you have handled the validation part!!! With this structure the form will not work as expected!!!

validation added

**Comment by mustafacihat** [comment]
good job thank you

**Pull request merged**
