### PR TITLE
User story 15 completed

### PR DESCRIPTION
**Pull request by Khasherdene1002**
User story 15 completed

### CODE REVIEW

**Review by asmikayr — APPROVED** [review]
Looks good! Great job.

**Review by mustafacihat — APPROVED** [review]
I would like to approve your pull request but, "Since both courseStatus and lessonGrade fields are not available in the input form, we should assign that information while updating that student." I could not have figured this point out completely if we successfully handled this part or not.

**Comment by mustafacihat** [comment]
@Khasherdene1002 could you have a chance to read my comment?

**Comment by Khasherdene1002** [comment]
Sorry I didn't see the second part of the UserStory . I thought it is approved.

**Pull request merged**
